parameters:
    pzs.twig.wcf_extension.class: Pzs\Bundle\WCFCoreBundle\Twig\WCFCoreExtension
    cache_service.class: Pzs\Bundle\WCFCoreBundle\Service\Cache\CacheService
    cache_service.provider: Doctrine\Common\Cache\FilesystemCache
    language_service.class: Pzs\Bundle\WCFCoreBundle\Service\Language\LanguageService
    language_repository.class: Pzs\Bundle\WCFCoreBundle\Repository\LanguageRepository
    language_repository.factory_argument: "PzsWCFCoreBundle:Language"
    language_category_repository.class: Pzs\Bundle\WCFCoreBundle\Repository\LanguageCategoryRepository
    language_category_repository.factory_argument: "PzsWCFCoreBundle:LanguageCategory"
    option_repository.class: Pzs\Bundle\WCFCoreBundle\Repository\OptionRepository
    option_repository.factory_argument: "PzsWCFCoreBundle:Option"
    option_category_repository.class: Pzs\Bundle\WCFCoreBundle\Repository\OptionCategoryRepository
    option_category_repository.factory_argument: "PzsWCFCoreBundle:OptionCategory"
    filesystem.class: Symfony\Component\Filesystem\Filesystem
    filesystem_factory.class: Pzs\Bundle\WCFCoreBundle\Util\FilesystemFactory

services:
    pzs.twig.wcf_extension:
        class: "%pzs.twig.wcf_extension.class%"
        arguments: 
            - "@language_service"
        tags:
            - { name: twig.extension }
    cache_service:
        class: "%cache_service.class%"
        provider: "%cache_service.source%"
        arguments:
            - "@cache_service.provider"
    filesystem:
        class: "%filesystem.class%"
        factory_class: "%filesystem_factory.class%"
        factory_method: get    
    option_service:
        class: "%option_service.class%"
        arguments:
            - "@option_repository"
            - "@option_category_repository"
            - "@cache_service"
            - "@filesystem"
    language_service:
        class: "%language_service.class%"
        arguments: 
            - "@language_repository"
            - "@language_category_repository"
            - "@cache_service"
    language_repository:
        class: "%language_repository.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method: "getRepository"
        arguments:
            - "@language_repository.factory_argument"
    language_category_repository:
        class: "%language_category_repository.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method: "getRepository"
        arguments:
            - "@language_category_repository.factory_argument"
    option_repository:
            class: "%option_repository.class%"
            factory_service: doctrine.orm.entity_manager
            factory_method: "getRepository"
            arguments:
                - "@option_repository.factory_argument"
    option_category_repository:
            class: "%option_category_repository.class%"
            factory_service: doctrine.orm.entity_manager
            factory_method: "getRepository"
            arguments:
                - "@option_category_repository.factory_argument"
